# config.yaml
ports:
  coordinator_results: 5554

workers:
  xrd:
    port: 5555
    health_port: 5556
    script: xrd_worker.py
  xrf:
    port: 5557
    health_port: 5558
    script: xrf_worker.py
  imaging:
    port: 5559
    health_port: 5560
    script: imaging_worker.py
  spectroradiometry:
    port: 5561
    health_port: 5562
    script: run_pyradiant.py

data:
  input_directory: /data/raw
  output_directory: /data/processed