# This is a basic workflow to help you get started with Actions

name: CD_MACOS

on: [push, pull_request]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  build_macos:
    # The type of runner that the job will run on
    runs-on: macos-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    - uses: actions/checkout@v2
    - run: git fetch --prune --unshallow
    - name: Setup Python 3.7
      uses: actions/setup-python@v1
      with:
        python-version: 3.7

    - name: Use Python Dependency Cache
      id: pip-cache
      uses: actions/cache@v1
      with:
        path: ~/Library/Caches/pip
        key: ${{ runner.os }}-pip-${{ hashFiles('T-View.spec') }}
        restore-keys: |
          ${{ runner.os }}-pip-
        
    - name: Install Pip Dependencies
      run: |
        pip install scipy python-dateutil pytest PyQt5 h5py PyQt5 lmfit mock pyshortcuts pyinstaller
        pip install --pre pyqtgraph

    - name: Run T-View from source to test and create version file
      run: python run_t_view.py test

    - name: Run PyInstaller
      run: pyinstaller T-View.spec

    - name: Clean Up Executable Folder
      run: |
        cd dist/T-View*
        cd Contents/MacOS
        rm QtQuick QtQml QtQmlmodels QtNetwork QtWebSockets libcrypto.1.0.0.dylib

    - name: Run T-View Executable
      run: |
        cd dist/T-View*
        cd Contents/MacOS
        ./run_t_view test

    - name: Compress App
      run: |
        cd dist
        export folderName=$(ls | grep T-View*.app)
        echo $folderName
        zip -r $folderName.zip $folderName
        du -sh $folderName.zip

    - name: Upload Compressed App to Dropbox
      env:
        DROPBOX_TOKEN: ${{ secrets.DROPBOX_TOKEN }}
      run: |
        pip install dropbox
        cd dist
        export compressedFile=$(ls | grep .zip)
        export targetFile='/develop/macos/'$compressedFile
        python ../scripts/dropbox_upload.py $compressedFile $targetFile